services:
  nginx:
    container_name: nginx-container
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - vault
    ports:
      - "8200:80"
    networks:
      - app-network

  vault:
    build:
      context: ../../vault
      dockerfile: Dockerfile.dev
    ports:
      - "8100:8100"
    depends_on:
      postgres:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy
    networks:
      - app-network

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    command: >
       -c ssl=on
       -c ssl_cert_file=/var/lib/postgresql/ssl/server.crt
       -c ssl_key_file=/var/lib/postgresql/ssl/server.key


  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine
    container_name: rabbitmq
    ports:
      - "5673:5672"  
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest  
      RABBITMQ_DEFAULT_PASS: guest 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - app-network
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 10s

  ui:
    build:
      context: ../../UI/remix
      dockerfile: Dockerfile.dev
    container_name: ui
    ports:
      - "3000:3000"
    networks:
      - app-network

 
volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_logs:

networks:
  app-network:
    driver: bridge